// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gradIPS
arma::vec gradIPS(const arma::vec& b, const arma::vec& d, const arma::mat& X, SEXP w, double treated_flag, const arma::vec& whs);
RcppExport SEXP _IPS_gradIPS(SEXP bSEXP, SEXP dSEXP, SEXP XSEXP, SEXP wSEXP, SEXP treated_flagSEXP, SEXP whsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type treated_flag(treated_flagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type whs(whsSEXP);
    rcpp_result_gen = Rcpp::wrap(gradIPS(b, d, X, w, treated_flag, whs));
    return rcpp_result_gen;
END_RCPP
}
// gradLIPS
arma::vec gradLIPS(const arma::vec& b, const arma::vec& d, const arma::vec& z, const arma::mat& X, SEXP w, const arma::vec& whs);
RcppExport SEXP _IPS_gradLIPS(SEXP bSEXP, SEXP dSEXP, SEXP zSEXP, SEXP XSEXP, SEXP wSEXP, SEXP whsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type whs(whsSEXP);
    rcpp_result_gen = Rcpp::wrap(gradLIPS(b, d, z, X, w, whs));
    return rcpp_result_gen;
END_RCPP
}
// kernelIPSdense
SEXP kernelIPSdense(const arma::mat& weights);
RcppExport SEXP _IPS_kernelIPSdense(SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelIPSdense(weights));
    return rcpp_result_gen;
END_RCPP
}
// kernelIPSexp
SEXP kernelIPSexp(const arma::mat& X, std::string X_trans);
RcppExport SEXP _IPS_kernelIPSexp(SEXP XSEXP, SEXP X_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< std::string >::type X_trans(X_transSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelIPSexp(X, X_trans));
    return rcpp_result_gen;
END_RCPP
}
// kernelIPSexpWeighted
SEXP kernelIPSexpWeighted(const arma::mat& X, std::string X_trans, const arma::vec& case_weights);
RcppExport SEXP _IPS_kernelIPSexpWeighted(SEXP XSEXP, SEXP X_transSEXP, SEXP case_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< std::string >::type X_trans(X_transSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type case_weights(case_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelIPSexpWeighted(X, X_trans, case_weights));
    return rcpp_result_gen;
END_RCPP
}
// kernelIPSind
SEXP kernelIPSind(const arma::mat& X);
RcppExport SEXP _IPS_kernelIPSind(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelIPSind(X));
    return rcpp_result_gen;
END_RCPP
}
// kernelIPSindWeighted
SEXP kernelIPSindWeighted(const arma::mat& X, const arma::vec& case_weights);
RcppExport SEXP _IPS_kernelIPSindWeighted(SEXP XSEXP, SEXP case_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type case_weights(case_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelIPSindWeighted(X, case_weights));
    return rcpp_result_gen;
END_RCPP
}
// kernelIPSproj
SEXP kernelIPSproj(const arma::mat& X);
RcppExport SEXP _IPS_kernelIPSproj(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelIPSproj(X));
    return rcpp_result_gen;
END_RCPP
}
// kernelIPSprojWeighted
SEXP kernelIPSprojWeighted(const arma::mat& X, const arma::vec& case_weights);
RcppExport SEXP _IPS_kernelIPSprojWeighted(SEXP XSEXP, SEXP case_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type case_weights(case_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelIPSprojWeighted(X, case_weights));
    return rcpp_result_gen;
END_RCPP
}
// kernelIPSDense
arma::mat kernelIPSDense(SEXP kernel);
RcppExport SEXP _IPS_kernelIPSDense(SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelIPSDense(kernel));
    return rcpp_result_gen;
END_RCPP
}
// linIPS
arma::mat linIPS(const arma::vec& bhat, const arma::vec& d, const arma::vec& pshat, const arma::mat& X, SEXP w, double treated_flag, const arma::vec& whs);
RcppExport SEXP _IPS_linIPS(SEXP bhatSEXP, SEXP dSEXP, SEXP pshatSEXP, SEXP XSEXP, SEXP wSEXP, SEXP treated_flagSEXP, SEXP whsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type bhat(bhatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pshat(pshatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type treated_flag(treated_flagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type whs(whsSEXP);
    rcpp_result_gen = Rcpp::wrap(linIPS(bhat, d, pshat, X, w, treated_flag, whs));
    return rcpp_result_gen;
END_RCPP
}
// linLIPS
arma::mat linLIPS(const arma::vec& bhat, const arma::vec& d, const arma::vec& z, const arma::vec& ipshat, const arma::mat& X, SEXP w, const arma::vec& whs);
RcppExport SEXP _IPS_linLIPS(SEXP bhatSEXP, SEXP dSEXP, SEXP zSEXP, SEXP ipshatSEXP, SEXP XSEXP, SEXP wSEXP, SEXP whsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type bhat(bhatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ipshat(ipshatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type whs(whsSEXP);
    rcpp_result_gen = Rcpp::wrap(linLIPS(bhat, d, z, ipshat, X, w, whs));
    return rcpp_result_gen;
END_RCPP
}
// objIPS
double objIPS(const arma::vec& b, const arma::vec& d, const arma::mat& X, SEXP w, double treated_flag, const arma::vec& whs);
RcppExport SEXP _IPS_objIPS(SEXP bSEXP, SEXP dSEXP, SEXP XSEXP, SEXP wSEXP, SEXP treated_flagSEXP, SEXP whsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type treated_flag(treated_flagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type whs(whsSEXP);
    rcpp_result_gen = Rcpp::wrap(objIPS(b, d, X, w, treated_flag, whs));
    return rcpp_result_gen;
END_RCPP
}
// objLIPS
double objLIPS(const arma::vec& b, const arma::vec& d, const arma::vec& z, const arma::mat& X, SEXP w, const arma::vec& whs);
RcppExport SEXP _IPS_objLIPS(SEXP bSEXP, SEXP dSEXP, SEXP zSEXP, SEXP XSEXP, SEXP wSEXP, SEXP whsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type whs(whsSEXP);
    rcpp_result_gen = Rcpp::wrap(objLIPS(b, d, z, X, w, whs));
    return rcpp_result_gen;
END_RCPP
}
// optimIPSCpp
Rcpp::List optimIPSCpp(const arma::vec& par, const arma::vec& d, const arma::mat& X, SEXP w, double treated_flag, const arma::vec& whs, int maxit, double abstol, double reltol);
RcppExport SEXP _IPS_optimIPSCpp(SEXP parSEXP, SEXP dSEXP, SEXP XSEXP, SEXP wSEXP, SEXP treated_flagSEXP, SEXP whsSEXP, SEXP maxitSEXP, SEXP abstolSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type treated_flag(treated_flagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type whs(whsSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optimIPSCpp(par, d, X, w, treated_flag, whs, maxit, abstol, reltol));
    return rcpp_result_gen;
END_RCPP
}
// weightIPSexp
arma::mat weightIPSexp(const arma::mat& X, std::string X_trans);
RcppExport SEXP _IPS_weightIPSexp(SEXP XSEXP, SEXP X_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< std::string >::type X_trans(X_transSEXP);
    rcpp_result_gen = Rcpp::wrap(weightIPSexp(X, X_trans));
    return rcpp_result_gen;
END_RCPP
}
// weightIPSind
arma::mat weightIPSind(const arma::mat& X);
RcppExport SEXP _IPS_weightIPSind(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(weightIPSind(X));
    return rcpp_result_gen;
END_RCPP
}
// weightIPSproj
arma::mat weightIPSproj(const arma::mat& X);
RcppExport SEXP _IPS_weightIPSproj(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(weightIPSproj(X));
    return rcpp_result_gen;
END_RCPP
}
// weightIPSproj_uniq
arma::mat weightIPSproj_uniq(const arma::mat& X, const arma::vec& wgt);
RcppExport SEXP _IPS_weightIPSproj_uniq(SEXP XSEXP, SEXP wgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wgt(wgtSEXP);
    rcpp_result_gen = Rcpp::wrap(weightIPSproj_uniq(X, wgt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IPS_gradIPS", (DL_FUNC) &_IPS_gradIPS, 6},
    {"_IPS_gradLIPS", (DL_FUNC) &_IPS_gradLIPS, 6},
    {"_IPS_kernelIPSdense", (DL_FUNC) &_IPS_kernelIPSdense, 1},
    {"_IPS_kernelIPSexp", (DL_FUNC) &_IPS_kernelIPSexp, 2},
    {"_IPS_kernelIPSexpWeighted", (DL_FUNC) &_IPS_kernelIPSexpWeighted, 3},
    {"_IPS_kernelIPSind", (DL_FUNC) &_IPS_kernelIPSind, 1},
    {"_IPS_kernelIPSindWeighted", (DL_FUNC) &_IPS_kernelIPSindWeighted, 2},
    {"_IPS_kernelIPSproj", (DL_FUNC) &_IPS_kernelIPSproj, 1},
    {"_IPS_kernelIPSprojWeighted", (DL_FUNC) &_IPS_kernelIPSprojWeighted, 2},
    {"_IPS_kernelIPSDense", (DL_FUNC) &_IPS_kernelIPSDense, 1},
    {"_IPS_linIPS", (DL_FUNC) &_IPS_linIPS, 7},
    {"_IPS_linLIPS", (DL_FUNC) &_IPS_linLIPS, 7},
    {"_IPS_objIPS", (DL_FUNC) &_IPS_objIPS, 6},
    {"_IPS_objLIPS", (DL_FUNC) &_IPS_objLIPS, 6},
    {"_IPS_optimIPSCpp", (DL_FUNC) &_IPS_optimIPSCpp, 9},
    {"_IPS_weightIPSexp", (DL_FUNC) &_IPS_weightIPSexp, 2},
    {"_IPS_weightIPSind", (DL_FUNC) &_IPS_weightIPSind, 1},
    {"_IPS_weightIPSproj", (DL_FUNC) &_IPS_weightIPSproj, 1},
    {"_IPS_weightIPSproj_uniq", (DL_FUNC) &_IPS_weightIPSproj_uniq, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_IPS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
